#-*-coding:utf-8-*-
import urllib2
import json
from datamodel.basic import *
"""
menu_body= {
     "button":[
      {
           "name":u"会员专区",
           "sub_button":[
            {
               "type":"click",
               "name":u"会员注册",
               "key":"PIC"
            },
             {
               "type":"click",
               "name":u"会员福利",
               "key":"AUDIO"
            },
              {
               "type":"click",
               "name":u"门店查询",
               "key":"ABOUT"
            },
               {
               "type":"click",
               "name":u"我的订单",
               "key":"ABOUT"
            }]
       },
      {
           "name":u"辣妈课程",
           "sub_button":[
            {
               "type":"click",
               "name":u"热门活动",
               "key":"ABOUT"
            },
             {
               "type":"click",
               "name":u"宝贝课程",
               "key":"ABOUT"
            },
              {
               "type":"click",
               "name":u"妈妈教室",
               "key":"ABOUT"
            },
              {
               "type":"click",
               "name":u"孕妈故事",
               "key":"ABOUT"
            } ]
       },
      {
           "name":u"高端社区",
               "type":"view",
               "url":"http://quan.qgc.qq.com/177147127"
       }]
 }
"""
menu_body={
    "button":[
        {
            "type":"view",
            "name":u"社区生活",
            "url":"http://wx.wsq.qq.com/177147127"
        },
        {
            "name":u"活动介绍",
            "sub_button":[
            {
                "type":"click",
                "name":u"关于活动",
                "key":"ABOUTEVENT"
            },
            {
                "type":"click",
                "name":u"参与活动",
                "key":"WANTJOIN"
            }]
        }
    ]
}
token=GetAccessToken()
print DeleteMemu(token)
print SetMenu(token,menu_body)